/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package activitysheet6;

import java.awt.Color;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
/**
 *
 * @author Allen James Laxamana
 */
public class GradeEncoding extends javax.swing.JFrame {

    /**
     * Creates new form GradeEncoding
     */
    public GradeEncoding() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblGradeEncoding = new javax.swing.JLabel();
        txtMidName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblMidName = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        lblSection = new javax.swing.JLabel();
        cmbBoxSection = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        lblSineSos = new javax.swing.JLabel();
        lblUnits = new javax.swing.JLabel();
        lblGrades = new javax.swing.JLabel();
        lblRemarks = new javax.swing.JLabel();
        lblPurCom = new javax.swing.JLabel();
        lblMmw = new javax.swing.JLabel();
        lblComProg = new javax.swing.JLabel();
        lblComOrg = new javax.swing.JLabel();
        lblDiscrete = new javax.swing.JLabel();
        lblAqua = new javax.swing.JLabel();
        lblNstp = new javax.swing.JLabel();
        txtSineSos = new javax.swing.JTextField();
        txtPurCom = new javax.swing.JTextField();
        txtMmw = new javax.swing.JTextField();
        txtComProg = new javax.swing.JTextField();
        txtFoLa = new javax.swing.JTextField();
        txtComOrg = new javax.swing.JTextField();
        lblFoLa = new javax.swing.JLabel();
        txtDiscrete = new javax.swing.JTextField();
        txtAqua = new javax.swing.JTextField();
        txtNstp = new javax.swing.JTextField();
        cmbBoxSineSos = new javax.swing.JComboBox<>();
        cmbBoxPurCom = new javax.swing.JComboBox<>();
        cmbBoxMmw = new javax.swing.JComboBox<>();
        cmbBoxComProg = new javax.swing.JComboBox<>();
        cmbBoxFoLa = new javax.swing.JComboBox<>();
        cmbBoxComOrg = new javax.swing.JComboBox<>();
        cmbBoxDiscrete = new javax.swing.JComboBox<>();
        cmbBoxAqua = new javax.swing.JComboBox<>();
        cmbBoxNstp = new javax.swing.JComboBox<>();
        lblRemSineSos = new javax.swing.JLabel();
        lblRemPurCom = new javax.swing.JLabel();
        lblRemMmw = new javax.swing.JLabel();
        lblRemComProg = new javax.swing.JLabel();
        lblRemFoLa = new javax.swing.JLabel();
        lblRemComOrg = new javax.swing.JLabel();
        lblRemDiscrete = new javax.swing.JLabel();
        lblRemAqua = new javax.swing.JLabel();
        lblRemNstp = new javax.swing.JLabel();
        lblFinal = new javax.swing.JLabel();
        txtFinal = new javax.swing.JTextField();
        lblFinalRem = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCompute = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jLabel2.setText("jLabel2");

        jLabel1.setText("jLabel1");

        jTextField8.setText("jTextField8");

        jTextField9.setText("jTextField9");

        jButton1.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblGradeEncoding.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGradeEncoding.setText("Grade Encoding");

        lblLastName.setText("Lastname");

        lblFirstName.setText("Firstname");

        lblMidName.setText("Middlename");

        lblNo.setText("Student No.:");

        jLabel3.setText("Student Name:");

        lblSection.setText("Section Name:");

        cmbBoxSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD1A", "SD1B" }));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTitle.setText("Course Title");

        lblSineSos.setText("SineSosyedad/Pelikulang Panlipunan (SINESOS)");

        lblUnits.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblUnits.setText("Units");

        lblGrades.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGrades.setText("Grades");

        lblRemarks.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblRemarks.setText("Remarks");

        lblPurCom.setText("Purposive Communication");

        lblMmw.setText("Mathematics in the Modern World");

        lblComProg.setText("Computer Programming II");

        lblComOrg.setText("Computer Organization and Architecture with Assembly Programming");

        lblDiscrete.setText("Discrete Math");

        lblAqua.setText("Aquatics");

        lblNstp.setText("National Service Training Program 2");

        txtSineSos.setEditable(false);
        txtSineSos.setText("3");
        txtSineSos.setToolTipText("");

        txtPurCom.setEditable(false);
        txtPurCom.setText("3");
        txtPurCom.setToolTipText("");

        txtMmw.setEditable(false);
        txtMmw.setText("3");
        txtMmw.setToolTipText("");

        txtComProg.setEditable(false);
        txtComProg.setText("3");
        txtComProg.setToolTipText("");

        txtFoLa.setEditable(false);
        txtFoLa.setText("3");
        txtFoLa.setToolTipText("");

        txtComOrg.setEditable(false);
        txtComOrg.setText("3");
        txtComOrg.setToolTipText("");

        lblFoLa.setText("Foreign Language");

        txtDiscrete.setEditable(false);
        txtDiscrete.setText("3");
        txtDiscrete.setToolTipText("");

        txtAqua.setEditable(false);
        txtAqua.setText("3");
        txtAqua.setToolTipText("");

        txtNstp.setEditable(false);
        txtNstp.setText("3");
        txtNstp.setToolTipText("");

        cmbBoxSineSos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.25", "1.50", "1.75", "2.0", "2.25", "2.50", "2.75", "3.0", "3.25", "3.50", "3.75", "4.0", "4.25", "4.50", "4.75", "5.0" }));
        cmbBoxSineSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxSineSosActionPerformed(evt);
            }
        });

        cmbBoxPurCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.25", "1.50", "1.75", "2.0", "2.25", "2.50", "2.75", "3.0", "3.25", "3.50", "3.75", "4.0", "4.25", "4.50", "4.75", "5.0" }));
        cmbBoxPurCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxPurComActionPerformed(evt);
            }
        });

        cmbBoxMmw.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.25", "1.50", "1.75", "2.0", "2.25", "2.50", "2.75", "3.0", "3.25", "3.50", "3.75", "4.0", "4.25", "4.50", "4.75", "5.0" }));
        cmbBoxMmw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxMmwActionPerformed(evt);
            }
        });

        cmbBoxComProg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.25", "1.50", "1.75", "2.0", "2.25", "2.50", "2.75", "3.0", "3.25", "3.50", "3.75", "4.0", "4.25", "4.50", "4.75", "5.0" }));
        cmbBoxComProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxComProgActionPerformed(evt);
            }
        });

        cmbBoxFoLa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.25", "1.50", "1.75", "2.0", "2.25", "2.50", "2.75", "3.0", "3.25", "3.50", "3.75", "4.0", "4.25", "4.50", "4.75", "5.0" }));
        cmbBoxFoLa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxFoLaActionPerformed(evt);
            }
        });

        cmbBoxComOrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.25", "1.50", "1.75", "2.0", "2.25", "2.50", "2.75", "3.0", "3.25", "3.50", "3.75", "4.0", "4.25", "4.50", "4.75", "5.0" }));
        cmbBoxComOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxComOrgActionPerformed(evt);
            }
        });

        cmbBoxDiscrete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.25", "1.50", "1.75", "2.0", "2.25", "2.50", "2.75", "3.0", "3.25", "3.50", "3.75", "4.0", "4.25", "4.50", "4.75", "5.0" }));
        cmbBoxDiscrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxDiscreteActionPerformed(evt);
            }
        });

        cmbBoxAqua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.25", "1.50", "1.75", "2.0", "2.25", "2.50", "2.75", "3.0", "3.25", "3.50", "3.75", "4.0", "4.25", "4.50", "4.75", "5.0" }));
        cmbBoxAqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxAquaActionPerformed(evt);
            }
        });

        cmbBoxNstp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.25", "1.50", "1.75", "2.0", "2.25", "2.50", "2.75", "3.0", "3.25", "3.50", "3.75", "4.0", "4.25", "4.50", "4.75", "5.0" }));
        cmbBoxNstp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxNstpActionPerformed(evt);
            }
        });

        lblRemSineSos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRemSineSos.setForeground(java.awt.Color.blue);
        lblRemSineSos.setText("PASSED");

        lblRemPurCom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRemPurCom.setForeground(java.awt.Color.blue);
        lblRemPurCom.setText("PASSED");

        lblRemMmw.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRemMmw.setForeground(java.awt.Color.blue);
        lblRemMmw.setText("PASSED");

        lblRemComProg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRemComProg.setForeground(java.awt.Color.blue);
        lblRemComProg.setText("PASSED");

        lblRemFoLa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRemFoLa.setForeground(java.awt.Color.blue);
        lblRemFoLa.setText("PASSED");

        lblRemComOrg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRemComOrg.setForeground(java.awt.Color.blue);
        lblRemComOrg.setText("PASSED");

        lblRemDiscrete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRemDiscrete.setForeground(java.awt.Color.blue);
        lblRemDiscrete.setText("PASSED");

        lblRemAqua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRemAqua.setForeground(java.awt.Color.blue);
        lblRemAqua.setText("PASSED");

        lblRemNstp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRemNstp.setForeground(java.awt.Color.blue);
        lblRemNstp.setText("PASSED");

        lblFinal.setText("Final Grade:");

        txtFinal.setEditable(false);

        lblFinalRem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFinalRem.setForeground(java.awt.Color.blue);
        lblFinalRem.setText("PASSED");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCompute.setText("Compute GWA");
        btnCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student No.", "Student Name", "GWA", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMmw)
                                    .addComponent(lblComOrg)
                                    .addComponent(lblFoLa)
                                    .addComponent(lblDiscrete)
                                    .addComponent(lblAqua)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(btnCompute))
                                        .addComponent(lblNstp)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFoLa, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtComProg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtMmw, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtComOrg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtDiscrete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtAqua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtNstp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPurCom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(txtSineSos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblFinal))))
                        .addGap(18, 18, 18)
                        .addComponent(lblGrades)
                        .addGap(18, 18, 18)
                        .addComponent(lblRemarks)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cmbBoxMmw, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblComProg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbBoxFoLa, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(cmbBoxComProg, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbBoxComOrg, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(cmbBoxDiscrete, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(cmbBoxAqua, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(cmbBoxNstp, javax.swing.GroupLayout.Alignment.TRAILING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(txtFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSineSos)
                                    .addComponent(lblPurCom))
                                .addGap(250, 250, 250)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbBoxSineSos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbBoxPurCom, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblRemSineSos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRemPurCom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRemMmw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRemComProg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRemFoLa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRemComOrg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRemDiscrete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRemAqua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRemNstp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblFinalRem))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblGradeEncoding)
                        .addGap(260, 260, 260))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblNo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(12, 12, 12)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSection)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbBoxSection, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMidName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(lblLastName)
                                .addGap(93, 93, 93)
                                .addComponent(lblFirstName)
                                .addGap(91, 91, 91)
                                .addComponent(lblMidName)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblGradeEncoding)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNo)
                    .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSection)
                    .addComponent(cmbBoxSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMidName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(lblFirstName)
                    .addComponent(lblMidName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(lblUnits)
                    .addComponent(lblGrades)
                    .addComponent(lblRemarks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRemSineSos)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSineSos)
                        .addComponent(txtSineSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbBoxSineSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPurCom)
                    .addComponent(txtPurCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBoxPurCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemPurCom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMmw)
                    .addComponent(txtMmw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBoxMmw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemMmw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComProg)
                    .addComponent(txtComProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBoxComProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemComProg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFoLa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoLa)
                    .addComponent(cmbBoxFoLa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemFoLa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComOrg)
                    .addComponent(cmbBoxComOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemComOrg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiscrete)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDiscrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbBoxDiscrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRemDiscrete)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAqua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAqua)
                    .addComponent(cmbBoxAqua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemAqua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNstp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNstp)
                    .addComponent(cmbBoxNstp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemNstp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinal)
                    .addComponent(txtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFinalRem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCompute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Ensure that all required fields are completed
        if (txtNo.getText().equals("") || txtLastName.getText().equals("") || txtFirstName.getText().equals("") || txtMidName.getText().equals("")) {
            // Display an error message
            JOptionPane.showMessageDialog(null, "Please fill all required fields.");
        }    
        else {
            // Concatenate the name and store it to an array
            String fullName = txtLastName.getText() + ", " + txtFirstName.getText() + " " + txtMidName.getText();
            // Store and compile the data into an array, convert them into a row
            DefaultTableModel tblInfo = (DefaultTableModel)jTable2.getModel();
            if (Double.parseDouble(txtFinal.getText()) < 4.0) {
                String studentInfo[] = {txtNo.getText(), fullName, (String) txtFinal.getText(), lblFinalRem.getText()}; 
                tblInfo.addRow(studentInfo);
            }
            else if (Double.parseDouble(txtFinal.getText()) > 4.0 && Double.parseDouble(txtFinal.getText()) < 5.0) {
                String studentInfo[] = {txtNo.getText(), fullName, (String) txtFinal.getText(), (lblFinalRem.getText() + " - Need to complete course/s")}; 
                tblInfo.addRow(studentInfo);
            }
            else {
                String studentInfo[] = {txtNo.getText(), fullName, (String) txtFinal.getText(), (lblFinalRem.getText() + " - Need to re-enroll course/s")};
                tblInfo.addRow(studentInfo);
            }
        }
        // Clear the textfields
        txtNo.setText("");
        txtLastName.setText("");
        txtFirstName.setText("");
        txtMidName.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeActionPerformed
        // Compute the GWA and display it to the textfield (5 decimal places)
        double total = (Double.parseDouble(cmbBoxAqua.getSelectedItem().toString()) + Double.parseDouble(cmbBoxComOrg.getSelectedItem().toString()) + Double.parseDouble(cmbBoxComProg.getSelectedItem().toString()) + Double.parseDouble(cmbBoxDiscrete.getSelectedItem().toString()) + Double.parseDouble(cmbBoxFoLa.getSelectedItem().toString()) + Double.parseDouble(cmbBoxMmw.getSelectedItem().toString()) + Double.parseDouble(cmbBoxNstp.getSelectedItem().toString()) + Double.parseDouble(cmbBoxPurCom.getSelectedItem().toString()) + Double.parseDouble(cmbBoxSineSos.getSelectedItem().toString())) / 9.0;
        DecimalFormat df = new DecimalFormat("#.#####");
        txtFinal.setText(String.valueOf(df.format(total)));
        
        // Alter the GWA's remarks
        if (Double.parseDouble(txtFinal.getText()) < 4.0) {
            lblFinalRem.setText("PASSED");
            lblFinalRem.setForeground(Color.blue);
        }
        else if (Double.parseDouble(txtFinal.getText()) > 4.0 && Double.parseDouble(txtFinal.getText()) < 5.0) {
            lblFinalRem.setText("INC");
            lblFinalRem.setForeground(Color.red);
        }
        else {
            lblFinalRem.setText("FAILED");
            lblFinalRem.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnComputeActionPerformed

    private void cmbBoxSineSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxSineSosActionPerformed
        // Display the appropriate remark depending on the grade
        if (Double.parseDouble(cmbBoxSineSos.getSelectedItem().toString()) < 4.0) {
            lblRemSineSos.setText("PASSED");
            lblRemSineSos.setForeground(Color.blue);
        }
        else if (Double.parseDouble(cmbBoxSineSos.getSelectedItem().toString()) > 4.0 && Double.parseDouble(cmbBoxSineSos.getSelectedItem().toString()) < 5.0) {
            lblRemSineSos.setText("INC");
            lblRemSineSos.setForeground(Color.red);
        }
        else {
            lblRemSineSos.setText("FAILED");
            lblRemSineSos.setForeground(Color.red);
        }
    }//GEN-LAST:event_cmbBoxSineSosActionPerformed

    private void cmbBoxPurComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxPurComActionPerformed
        // Display the appropriate remark depending on the grade
        if (Double.parseDouble(cmbBoxPurCom.getSelectedItem().toString()) < 4.0) {
            lblRemPurCom.setText("PASSED");
            lblRemPurCom.setForeground(Color.blue);
        }
        else if (Double.parseDouble(cmbBoxPurCom.getSelectedItem().toString()) > 4.0 && Double.parseDouble(cmbBoxPurCom.getSelectedItem().toString()) < 5.0) {
            lblRemPurCom.setText("INC");
            lblRemPurCom.setForeground(Color.red);
        }
        else {
            lblRemPurCom.setText("FAILED");
            lblRemPurCom.setForeground(Color.red);
        }
    }//GEN-LAST:event_cmbBoxPurComActionPerformed

    private void cmbBoxMmwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxMmwActionPerformed
        // Display the appropriate remark depending on the grade
        if (Double.parseDouble(cmbBoxMmw.getSelectedItem().toString()) < 4.0) {
            lblRemMmw.setText("PASSED");
            lblRemMmw.setForeground(Color.blue);
        }
        else if (Double.parseDouble(cmbBoxMmw.getSelectedItem().toString()) > 4.0 && Double.parseDouble(cmbBoxMmw.getSelectedItem().toString()) < 5.0) {
            lblRemMmw.setText("INC");
            lblRemMmw.setForeground(Color.red);
        }
        else {
            lblRemMmw.setText("FAILED");
            lblRemMmw.setForeground(Color.red);
        }
    }//GEN-LAST:event_cmbBoxMmwActionPerformed

    private void cmbBoxComProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxComProgActionPerformed
        // Display the appropriate remark depending on the grade
        if (Double.parseDouble(cmbBoxComProg.getSelectedItem().toString()) < 4.0) {
            lblRemComProg.setText("PASSED");
            lblRemComProg.setForeground(Color.blue);
        }
        else if (Double.parseDouble(cmbBoxComProg.getSelectedItem().toString()) > 4.0 && Double.parseDouble(cmbBoxComProg.getSelectedItem().toString()) < 5.0) {
            lblRemComProg.setText("INC");
            lblRemComProg.setForeground(Color.red);
        }
        else {
            lblRemComProg.setText("FAILED");
            lblRemComProg.setForeground(Color.red);
        }
    }//GEN-LAST:event_cmbBoxComProgActionPerformed

    private void cmbBoxFoLaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxFoLaActionPerformed
        // Display the appropriate remark depending on the grade
        if (Double.parseDouble(cmbBoxFoLa.getSelectedItem().toString()) < 4.0) {
            lblRemFoLa.setText("PASSED");
            lblRemFoLa.setForeground(Color.blue);
        }
        else if (Double.parseDouble(cmbBoxFoLa.getSelectedItem().toString()) > 4.0 && Double.parseDouble(cmbBoxFoLa.getSelectedItem().toString()) < 5.0) {
            lblRemFoLa.setText("INC");
            lblRemFoLa.setForeground(Color.red);
        }
        else {
            lblRemFoLa.setText("FAILED");
            lblRemFoLa.setForeground(Color.red);
        }
    }//GEN-LAST:event_cmbBoxFoLaActionPerformed

    private void cmbBoxComOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxComOrgActionPerformed
        // Display the appropriate remark depending on the grade
        if (Double.parseDouble(cmbBoxComOrg.getSelectedItem().toString()) < 4.0) {
            lblRemComOrg.setText("PASSED");
            lblRemComOrg.setForeground(Color.blue);
        }
        else if (Double.parseDouble(cmbBoxComOrg.getSelectedItem().toString()) > 4.0 && Double.parseDouble(cmbBoxComOrg.getSelectedItem().toString()) < 5.0) {
            lblRemComOrg.setText("INC");
            lblRemComOrg.setForeground(Color.red);
        }
        else {
            lblRemComOrg.setText("FAILED");
            lblRemComOrg.setForeground(Color.red);
        }
    }//GEN-LAST:event_cmbBoxComOrgActionPerformed

    private void cmbBoxDiscreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxDiscreteActionPerformed
        // Display the appropriate remark depending on the grade
        if (Double.parseDouble(cmbBoxDiscrete.getSelectedItem().toString()) < 4.0) {
            lblRemDiscrete.setText("PASSED");
            lblRemDiscrete.setForeground(Color.blue);
        }
        else if (Double.parseDouble(cmbBoxDiscrete.getSelectedItem().toString()) > 4.0 && Double.parseDouble(cmbBoxDiscrete.getSelectedItem().toString()) < 5.0) {
            lblRemDiscrete.setText("INC");
            lblRemDiscrete.setForeground(Color.red);
        }
        else {
            lblRemDiscrete.setText("FAILED");
            lblRemDiscrete.setForeground(Color.red);
        }
    }//GEN-LAST:event_cmbBoxDiscreteActionPerformed

    private void cmbBoxAquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxAquaActionPerformed
        // Display the appropriate remark depending on the grade
        if (Double.parseDouble(cmbBoxAqua.getSelectedItem().toString()) < 4.0) {
            lblRemAqua.setText("PASSED");
            lblRemAqua.setForeground(Color.blue);
        }
        else if (Double.parseDouble(cmbBoxAqua.getSelectedItem().toString()) > 4.0 && Double.parseDouble(cmbBoxAqua.getSelectedItem().toString()) < 5.0) {
            lblRemAqua.setText("INC");
            lblRemAqua.setForeground(Color.red);
        }
        else {
            lblRemAqua.setText("FAILED");
            lblRemAqua.setForeground(Color.red);
        }
    }//GEN-LAST:event_cmbBoxAquaActionPerformed

    private void cmbBoxNstpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxNstpActionPerformed
        // Display the appropriate remark depending on the grade
        if (Double.parseDouble(cmbBoxNstp.getSelectedItem().toString()) < 4.0) {
            lblRemNstp.setText("PASSED");
            lblRemNstp.setForeground(Color.blue);
        }
        else if (Double.parseDouble(cmbBoxNstp.getSelectedItem().toString()) > 4.0 && Double.parseDouble(cmbBoxNstp.getSelectedItem().toString()) < 5.0) {
            lblRemNstp.setText("INC");
            lblRemNstp.setForeground(Color.red);
        }
        else {
            lblRemNstp.setText("FAILED");
            lblRemNstp.setForeground(Color.red);
        }
    }//GEN-LAST:event_cmbBoxNstpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeEncoding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeEncoding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeEncoding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeEncoding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeEncoding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompute;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbBoxAqua;
    private javax.swing.JComboBox<String> cmbBoxComOrg;
    private javax.swing.JComboBox<String> cmbBoxComProg;
    private javax.swing.JComboBox<String> cmbBoxDiscrete;
    private javax.swing.JComboBox<String> cmbBoxFoLa;
    private javax.swing.JComboBox<String> cmbBoxMmw;
    private javax.swing.JComboBox<String> cmbBoxNstp;
    private javax.swing.JComboBox<String> cmbBoxPurCom;
    private javax.swing.JComboBox<String> cmbBoxSection;
    private javax.swing.JComboBox<String> cmbBoxSineSos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lblAqua;
    private javax.swing.JLabel lblComOrg;
    private javax.swing.JLabel lblComProg;
    private javax.swing.JLabel lblDiscrete;
    private javax.swing.JLabel lblFinal;
    private javax.swing.JLabel lblFinalRem;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFoLa;
    private javax.swing.JLabel lblGradeEncoding;
    private javax.swing.JLabel lblGrades;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMidName;
    private javax.swing.JLabel lblMmw;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblNstp;
    private javax.swing.JLabel lblPurCom;
    private javax.swing.JLabel lblRemAqua;
    private javax.swing.JLabel lblRemComOrg;
    private javax.swing.JLabel lblRemComProg;
    private javax.swing.JLabel lblRemDiscrete;
    private javax.swing.JLabel lblRemFoLa;
    private javax.swing.JLabel lblRemMmw;
    private javax.swing.JLabel lblRemNstp;
    private javax.swing.JLabel lblRemPurCom;
    private javax.swing.JLabel lblRemSineSos;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JLabel lblSection;
    private javax.swing.JLabel lblSineSos;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUnits;
    private javax.swing.JTextField txtAqua;
    private javax.swing.JTextField txtComOrg;
    private javax.swing.JTextField txtComProg;
    private javax.swing.JTextField txtDiscrete;
    private javax.swing.JTextField txtFinal;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFoLa;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMidName;
    private javax.swing.JTextField txtMmw;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtNstp;
    private javax.swing.JTextField txtPurCom;
    private javax.swing.JTextField txtSineSos;
    // End of variables declaration//GEN-END:variables
}
